### ISSUE TITLE
dimensional weight shipping fields

### ISSUE THREAD

**Issue by harryjl** [chaddro/EasyPopulate-4.0#21]
Hi...
I would like to know if there's a new version coming soon with the capability of create new records and update it including the new dimensional weight shipping fields requirements.
We have installed on our store the EP 1.5x version and were looking to update to the EP4.0, but neither one have this capability.
If no, what's the best way to get around ?

thank you.

**Comment by mc12345678** [comment]
If the applicable field(s) are in the products table then they can be included as a custom field in the configuration menu. If not, then identification of which table has these fields and what the field names are would make it possible to add.

**Comment by mc12345678** [comment]
What program are you using that offers the new dimensional weight shipping fields?

**Comment by harryjl** [comment]
It some sort of plugin for ZenCart.

It calls AuctionInc

http://www.auctioninc.com/info/page/zencart_auctioninc_settings

I'm nor sure how it works, it was installed here.





As always... Good Welding,

Harry JL

Graphic Designer

[image: arc-zone-email-sig.png]
<https://www.arc-zone.com/?utm_source=email&utm_medium=email&utm_campaign=homepage%20signature>

THE WELDING ACCESSORY EXPERTS

------------------------------

Worldwide:  (760) 931-1500

Toll Free US:  (800) 944-2243

Email:  harry@arc-zone.com

Website:  www.Arc-Zone.com
<https://www.arc-zone.com/?utm_source=utm&utm_medium=email&utm_campaign=signature?utm_source=utm&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature?utm_source=utm&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

View our entire Product Line
<https://www.arc-zone.com/pdf/Arc-Zone_Line_Card_2015.pdf?utm_source=gmail%20email%20signature%20&utm_medium=email%20&utm_campaign=gmail%20signature%20linecard>

Subscribe to The Metal Mashup
<http://visitor.r20.constantcontact.com/manage/optin?v=001d1nhV3sbSz9Rj2tMDNhglAEPnFCSLfCtQNB7Y7NdyhZ70Zal0hpk44Qe5qHyf-GC4btzaRlpSA1xMlQcMyHV4LPkxlYKKzcKQLhONoUJejw%3D&utm_source=email%20signature&utm_medium=email&utm_campaign=signup%20metal%20mashup>
------------------------------

<https://instagram.com/arc_zone/?utm_source=email%20&utm_medium=email%20&utm_campaign=instagram%20signature%20>

<https://www.facebook.com/ArcZone?utm_source=email%20&utm_medium=email%20&utm_campaign=facebook%20signature%20>

<https://twitter.com/arczone?utm_source=email%20&utm_medium=email%20&utm_campaign=twitter%20signature%20>

<https://www.youtube.com/user/ArcZoneVideos?utm_source=email%20&utm_medium=email%20&utm_campaign=youtube%20signature%20>

**Comment by harryjl** [comment]
Hello again...
Can I include a custom field into Attributes csv file? I would like to update not only the price but also the Part# for the attribute.
Thanks for reading!

**Comment by mc12345678** [comment]
Was finally able (site allowed and had a moment of time) to download the applicable ZC files to be able to install this additional software.  Based on review of the instruction manual for the Rates API the below fields are added to the products table.  To retrieve/set these values (after installation of the auctioninc software), they should be added to the custom fields section of the configuration->Easy Populate v4 menu separated by a comma for each desired field (without the single quote) to be seen/updated. 

```php
	'actioninc_calcmethod',
	'actioninc_length',
	'actioninc_width',
	'actioninc_height',
	'actioninc_package',
	'actioninc_origincode',
	'actioninc_insurable',
	'actioninc_handlingcode',
	'actioninc_fixeddollaramount',
	'actioninc_servicecodes',
	'actioninc_specialaccessorialfees',
	'actioninc_fixedfeecode',
	'actioninc_fixedfee1',
	'actioninc_fixedfee2'

```

So for the above, to obtain and set the length, width, and height of each "package" (product), then the custom fields entry should be:
actioninc_length, actioninc_width, actioninc_height

This will result in the three fields being populated in a full products export (or export of applicable products) and if the fields remain in the import file, then the values associated will be assigned to the applicable product.  Note the fields will individually appear in the exported file as v_actioninc_length, v_actioninc_width, v_actioninc_height.  These fields will each have its own column and associated data below for existing entries.  To see what is expected to be entered to support import, I defer back to the EP4 instructions of "trial-and-error" where an entry is first manually made in ZC, an export performed that includes that manual entry and review of the results as compare to what was entered.  This process should provide indication of what needs to be entered into the import file to support further calculations/population.

I do not know the dependency of the other fields listed above, but each field can be included through the above process either one at a time, or all at once... 

I recommend further inquiry about the operation of that plugin be directed to the original authors.  There is technically no further action necessary to incorporate use of EP4 with that plugin.  It is possible to customize options to possibly simplify the routine use; but that is outside the scope of this.

Closing this issue.
