### ISSUE TITLE
Categories delimeter

### ISSUE THREAD

**Issue by mesnitu** [chaddro/EasyPopulate-4.0#26]
$category_delimiter = "\x5e" , doesn't seen to be splitting and ends up in names length error 
Changing to : 
$category_delimiter = '\x5e' , it's ok 
Categories example:
select the forum that you want^to visit from the selection

**Comment by mesnitu** [comment]
Please ignore this last issue. It's a issue for me, but I'm getting all kind of different results, so what I've mentioned above, it's not ok either.

**Comment by mesnitu** [comment]
Ok, it's a issue out of the box. 
Started from scratch : 
Deleted all admin files and downloaded them again from the shop with Easy Populate 4.0.22 - Beta 6-10-2012 ( just the EP4, no bookx fields ) 

Export all products, import all products -> OK 

Deleted all related Easy Populate 4.0.22 - Beta 6-10-2012, and installed the Easy Populate 4.0.33a - Beta 02-29-2016

Import the same file -> Not Ok

```
SKIPPED! - Model: 9789898087973 - Category name: "Desenvolvimento Pessoal^Espiritualidade" exceeds max. length: 32
SKIPPED! - Model: 9789897070372 - Category name: "Infantil/Juvenil^Infantil / Juvenil" exceeds max. length: 32
```

Not only this skipped cat because of name length, but actually **is not splitting any categories** at all. All the others that have child categories are not split , but they don't exceed the length

**Comment by mesnitu** [comment]
If I use what' s on Easy Populate 4.0.22  import, the cat gets split  : 
`$categories_names_array[$lang['id']] = mb_split('\x5e',$items[$filelayout['v_categories_name_'.$lang['id']]]);`

On this version, only using explode
`$categories_names_array[$lang['id']] = explode($categories_delimiter,$items[$filelayout['v_categories_name_'.$lang['id']]]);`

Opening on libreoffice, the character is ut8 , opening on notepad++ also says utf8.

**Comment by mc12345678** [comment]
On your EP4 admin screen upper right hand corner, do you have the following message: 
> 'mb_internal_encoding not available'
Is your store using UTF8? Database, language, etc..?

**Comment by mesnitu** [comment]
I don't see that , just this ( plus the database and installed language that I posted above : 
```
Configuration Settings
Upload Directory: admin/temp/
Verbose Feedback: TRUE
Split Records: 2000
Execution Time: 300
Convert Curly Quotes: No Change
Convert Char 0x92: Basic
Enable Products Metatags: 1
Enable Products Music: 0
```

If I check this : 
```
echo mb_regex_encoding();
			
            $categories_names_array[$lang['id']] = mb_split( $categories_delimiter, $items[$filelayout['v_categories_name_' . $lang['id']]]);
```

I'll see this : 
```
UTF-8
Array
(
    [2] => Array
        (
            [0] => Desenvolvimento Pessoal^Espiritualidade
        )

)
```

**Comment by mesnitu** [comment]
All database is in utf8_general_ci, except some tables like Ceon , and reward points, that have latin_1

**Comment by mc12345678** [comment]
> If I use what' s on Easy Populate 4.0.22 import, the cat gets split : 
 $categories_names_array[$lang['id']] = mb_split('\x5e',$items[$filelayout['v_categories_name_'.$lang['id']]]); 

> On this version, only using explode
 $categories_names_array[$lang['id']] = explode($categories_delimiter,$items[$filelayout['v_categories_name_'.$lang['id']]]); 

> Opening on libreoffice, the character is ut8 , opening on notepad++ also says utf8. 

So saying that both of the above work without issue, but not a mix of the two?

**Comment by mesnitu** [comment]
On mb_split , using $categories_delimeter.... doesn't . 
**THis works **
```
$categories_names_array[$lang['id']] = mb_split('\x5e',$items[$filelayout['v_categories_name_'.$lang['id']]]);

$categories_names_array[$lang['id']] = explode($categories_delimiter,$items[$filelayout['v_categories_name_'.$lang['id']]]);
```

**This doesn't **
`$categories_names_array[$lang['id']] = mb_split($categories_delimiter,$items[$filelayout['v_categories_name_'.$lang['id']]]);`

**Comment by mesnitu** [comment]
But it looks like I'm the one with this issue....

**Comment by mesnitu** [comment]
Just one more thing: at exporting this categories,  they get split

**Comment by mc12345678** [comment]
To clarify, if while using the current software you export a file then turn around and import the file, then there is no problem?
If you export a file then perhaps modify/create a category combination, is it successful or does the problem return?

**Comment by mesnitu** [comment]
**The only way it works** is using the **explode** or **mb_split('\x5e'**

What I didn't test while testing with EP022  was to replace the '\x5e' with $categorie_delimeter to see what happened. 

But this is some sort of encoding issue, very hard to detect ,I imagine. 
I'm on windows 10 ( while kde5 matures a bit ), using LibreOffice. Database is utf8, opening the files is utf8. 

But even the opening file doesn't matter, cause if I do a export / import directly,  it doesn't work either. 
So could it be on writing the file from database to the the folder ? 

But I had to move on. In the bookx genres, I'm actually using the '\x5e', so the genres, authors, etc, are split. 

So... don't know what to say more. 
I've done some mb_detect_encoding,etc... all return utf8 

But if no one is  issuing this, here or the forum....don't see how to replicate this. 


`

**Comment by mc12345678** [comment]
This issue has been corrected through the use of preg_quote on $categories_delimiter in the import code in version 4.0.34.a specifically at commit: 23d9b848cfeee30c300b2e940948651b30a62005.
